### ISSUE TITLE
Repo structure can be refined for documentation

### ISSUE THREAD

**Issue by heyhaleema** [AI4VBH/AIDE#1]
We could refine the current repo structure ahead of the training documentation addition, for example:

<pre/>
AIDE/
├─ README.md
assets/
├─ add-new-user.gif
├─ organisation-chart.png
├─ approvals-process.png
documentation/
├─ training/
│  ├─ aide-lifecycle.png
│  ├─ aide-admin.md
│  ├─ aide-superuser.md
│  ├─ aide-app-store-admin.md
│  ├─ aide-app-developer.md
│  ├─ aide-clinician.md
├─ templates/
│  ├─ aide-admin-approval-checklist.md
│  ├─ quality-assurance-checklist.md
│  ├─ data-processing-agreement.docx
│  ├─ model-card.yaml
</pre>

@Jaws785 and @Lucrezia-Cester - What do you think? I've given some examples of files to be stored in each, but these are just rough suggestions.
@JoeBatt1989 - We've initially discussed separating the training documentation by role (vs. function), but it'd be good to get your thoughts on this, too. 

Eventually, these documents should be linked to Read the Docs (or something similar).

**Comment by Lucrezia-Cester** [comment]
Hi @heyhaleema, I am a bit confused about the distinction between assets and documentation. Would it be possible to post here that diagram that we drew by hand? Just personally I would find it useful to reference it.

**Comment by heyhaleema** [comment]
Closed by #5.
