### ISSUE TITLE
Links to images broken in aide-admin.md

### ISSUE THREAD

**Issue by tomaroberts** [AI4VBH/AIDE#16]
Small issue – links to images broken: see https://github.com/AI4VBH/AIDE/blob/main/documentation/training/v0.2/aide-admin.md#querying-application-executions-based-on-a-study-uid

Screenshot:

![image](https://user-images.githubusercontent.com/15610752/204312598-6a25e5b3-1219-4f8d-93b0-dae8bbcb114c.png)

**Comment by heyhaleema** [comment]
@tomaroberts Closing this issue as we've now removed that document/v0.2 documentation after merging #24.
