### ISSUE TITLE
Check AIDE docs website doesn't break when editing the repo

### ISSUE THREAD

**Issue by Lucrezia-Cester** [AI4VBH/AIDE#44]
Hi @JoeBatt1989, @heyhaleema, @JillJarvis , there is a GitHub action that ensures the AIDE docs website updates automatically when you edit the repo. I have notices many docs have been added and approved to the repo but they have now "broken" the structure of the website as jupyterbook wants the folders and files structured in a particular way. 

I will now work on re-structuring the repo, but we all need to be aware of how the structure of added file should look like so that I don't need to continuosly re-do the same tasks to mantain the repo.

To this regard I suggest to read how the jupyterbook should be structured https://jupyterbook.org/en/stable/start/create.html include me as reviewer of PRs before merging.

**Comment by heyhaleema** [comment]
Resolved/updated by #43.
